### Pandas - Dataframe and Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis cleaning. It provides two primary data structure: Series and DataFrame. A Series is a one-dimensional array-like object, while a dataframe is a two dimensional, size-mutable and potentially heterogeneous tabular data structure with labeled axes (rows and columns)

In [2]:
import sys
print(sys.executable)

/Users/priyansh/dev/python/playground/venv/bin/python

In [2]:
import pandas as pd

data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
## Create a series from dictionary elements

data={'a':1, 'b':2, 'c': 3}
series = pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64

In [4]:
data = [10,20,30]
index=['a','b','c']

pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [6]:
## Dataframe

## Create a dataframe from dict of list

data = {
    'Name': ['Priyansh', 'Utsav', 'Ashish'],
    'Age': [27, 26, 27],
    'City': ['Bangalore', 'Kolkata', 'Santragachi']
}

df = pd.DataFrame(data)
print(df)

       Name  Age         City
0  Priyansh   27    Bangalore
1     Utsav   26      Kolkata
2    Ashish   27  Santragachi

In [7]:
## Create a dataframe from a list of dictionary

data = [
    { 'Name': 'Priyansh', 'Age': 27, 'City': 'Bangalore'},
    { 'Name': 'Utsav', 'Age': 26, 'City': 'Kolkata'},
    { 'Name': 'Ashish', 'Age': 27, 'City': 'Santragachi'}
]

print(pd.DataFrame(data))

       Name  Age         City
0  Priyansh   27    Bangalore
1     Utsav   26      Kolkata
2    Ashish   27  Santragachi

In [8]:
df.head(2)

       Name  Age       City
0  Priyansh   27  Bangalore
1     Utsav   26    Kolkata

In [9]:
df.tail(2)

     Name  Age         City
1   Utsav   26      Kolkata
2  Ashish   27  Santragachi

In [11]:
## Accessing data from dataframe

print(df['Name'])
print(type(df['Name']))

0    Priyansh
1       Utsav
2      Ashish
Name: Name, dtype: object
<class 'pandas.core.series.Series'>

In [13]:
df.loc[0]

Name     Priyansh
Age            27
City    Bangalore
Name: 0, dtype: object

In [14]:
df.loc[0][0]

'Priyansh'

In [15]:
df.iloc[0]

Name     Priyansh
Age            27
City    Bangalore
Name: 0, dtype: object

In [16]:
df.at[0, 'Age']

27

In [18]:
df.iat[1, 2]

'Kolkata'

In [19]:
## Data Manipulation with data frames

df

       Name  Age         City
0  Priyansh   27    Bangalore
1     Utsav   26      Kolkata
2    Ashish   27  Santragachi

In [28]:
df['Salary'] = [1000,2000,3000]

In [21]:
df

       Name  Age         City  Salary
0  Priyansh   27    Bangalore    1000
1     Utsav   26      Kolkata    2000
2    Ashish   27  Santragachi    3000

In [29]:
df.drop('Salary', axis = 1, inplace=True)

In [30]:
df

       Name  Age         City
0  Priyansh   27    Bangalore
1     Utsav   26      Kolkata
2    Ashish   27  Santragachi

In [31]:
df['Age'] = df['Age'] + 1

In [32]:
df

       Name  Age         City
0  Priyansh   28    Bangalore
1     Utsav   27      Kolkata
2    Ashish   28  Santragachi